### ISSUE TITLE
spring-native-image example not working as Maven 3.8.5 is not found

### ISSUE THREAD

**Issue by deors** [graalvm/graalvm-demos#158]
While building the native image for sprint-native-image, it fails in downloading Maven 3.8.5 which is not available at https://dlcdn.apache.org/maven/maven-3
It must be replaced with 3.8.6 and the correct checksum.
I can provide a PR fixing the issue if necessary.

**Comment by olyagpl** [comment]
Hi @deors. The demo is being tested with GitHub actions on Ubuntu 22.04.1 and maven-jar-plugin:3.3.0. Testing locally with 3.8.5 builds successfully.

**Comment by deors** [comment]
I think that the issue presents when Maven 3.8.5 cannot be found locally and the wrapper tries to download it. If it is already in the local box the wrapper doesn't download it again. Could it be your case?

**Comment by olyagpl** [comment]
Right, this is my case. Feel free to provide a PR fixing the issue!

**Comment by deors** [comment]
I apologize for not being able to comment before. This was a few months ago. Currently Maven Wrapper is configured with 3.9.3 in the spring-native-image demo.

**Comment by olyagpl** [comment]
Thanks for update!
