### ISSUE TITLE
Improve the error message when GraalVM version can't be found.

### ISSUE THREAD

**Issue by olyagpl** [graalvm/graalvm-demos#169]
When the **Run graalvm/setup-graalvm@v1** job fails with `Error: Unexpected HTTP response: 404`, it means the GraalVM release can't be found. The error message should be improved. See https://github.com/graalvm/graalvm-demos/actions/runs/3714185680/jobs/6297758721.

My mistake was to use 22.3 as the version string instead of 22.3.0.

**Comment by fniephaus** [comment]
Fixed via https://github.com/graalvm/setup-graalvm/commit/4aba115fa5a252b6991d4acc2003118e93c62e9e.
