### ISSUE TITLE
native-list-dir polyglot demo is not the same as the plain Java one

### ISSUE THREAD

**Issue by MarianMacik** [graalvm/graalvm-demos#34]
Hi,

I have been going through some tutorials and found out that [according to the documentation](https://www.graalvm.org/docs/examples/native-list-dir/#polyglot-capabilities), the `ExtListDir` Java/JavaScript polyglot demo should behave the same as the `ListDir` Java-only one.

However, you cannot pass the directory to browse to the polyglot one because it will simply alter the JavaScript function which is not what the point of the demo is.

Compare the 2 demos:

https://github.com/graalvm/graalvm-demos/blob/5ed4b1ff8d46b4d95eebfc0b89a9e3bc3bb9ceaa/native-list-dir/ExtListDir.java#L51-L66

See line 55, we are changing the body of the JavaScript function.

But in the Java-only demo, we change the root of the traversal:

https://github.com/graalvm/graalvm-demos/blob/5ed4b1ff8d46b4d95eebfc0b89a9e3bc3bb9ceaa/native-list-dir/ListDir.java#L51-L60

I would just alter this part and will leave system outs as they are now.

Can I proceed with this change?

Thanks

P.S. I can also do #4 as a part of this.

**Comment by MarianMacik** [comment]
@vjovanov or anybody?

**Comment by vjovanov** [comment]
@shelajev this seems to be your example.
