### ISSUE TITLE
graalpython-notebook-example: issue building and running demo

### ISSUE THREAD

**Issue by neomatrix369** [graalvm/graalvm-demos#94]
On the back of the PR #93, the `graalpython-notebook-example` (see https://github.com/graalvm/graalvm-demos/tree/master/graalpython-notebook-example) gives the below issues:

I came across a couple of errors when trying to run `graalpython-notebook-example` in a clean environment (docker container):
- Buildtime when trying to build the environment using the command `/graalvm-demos/graalpython-notebook-example/venv/bin/graalpython -Im ensurepip --upgrade --default-pip`:
[graalpython-notebook-example-jre-related-error.logs.zip](https://github.com/graalvm/graalvm-demos/files/7314763/graalpython-notebook-example-jre-related-error.logs.zip)

- Runtime when running the app using `mvn exec:java`:
![graalpython-notebook-example-numpy-missing](https://user-images.githubusercontent.com/1570917/136638522-8438f0ac-43ef-456d-ab77-81e6c463ed7a.png)

I did amend the `pom.xml` file, to install `numpy` under the `prepare-venv` profile (see https://github.com/graalvm/graalvm-demos/pull/93/commits/610ee5c4e539700116b8770af37c68c4b05a9b6a) but it had no effect (I ran `mvn clean compile` after manually deleting the `venv` folder).

Two other threads of conversations on the same topic:

- https://github.com/graalvm/graalvm-demos/pull/93#pullrequestreview-776503712
- https://github.com/graalvm/graalvm-demos/pull/93#issuecomment-940210974

**Comment by neomatrix369** [comment]
Is it possible to preload these dependencies before the user runs the `mvn` commands? I would like to pre-bake them into the image, so when the `mvn` commands are run, those libraires are found by it and it goes further and shows the nice GUI

**Comment by neomatrix369** [comment]
Hey @timfel , is there a way to install python packages in a `venv` environment but pull the packages off the local cache or local package repository - so we don't have to recompile and build it again?

I'm thinking of this command:

```
graalpython -m ginstall install matplotlib,Pillow,pandas
```

but with some flag like this:

```
graalpython -m ginstall install matplotlib,Pillow,pandas --use-local-cache

or 

graalpython -m ginstall install matplotlib,Pillow,pandas --install-from-local-repo
```

**Comment by neomatrix369** [comment]
Fixed via ea0a6c8, b6011bf

**Comment by timfel** [comment]
> Hey @timfel , is there a way to install python packages in a `venv` environment but pull the packages off the local cache or local package repository - so we don't have to recompile and build it again?

Right now no, we're working on having something like this available sometime next year

**Comment by neomatrix369** [comment]
> > Hey @timfel , is there a way to install python packages in a `venv` environment but pull the packages off the local cache or local package repository - so we don't have to recompile and build it again?
> 
> Right now no, we're working on having something like this available sometime next year

That's good to hear, for the time being we will try to make do of what we have, please keep us posted.
