### ISSUE TITLE
galaaz-ggplot: issue with building and running demo

### ISSUE THREAD

**Issue by neomatrix369** [graalvm/graalvm-demos#95]
On the back of the PR #93, after installing **TruffleRuby** via the `gu` tool and following the steps mentioned on https://github.com/graalvm/graalvm-demos/tree/master/galaaz-ggplot#introduction, the step to install the `rspec` gem initially failed due to the absence (or not being able to find these files:

```
libssl.so.10
libcrypto.so.10
```

Later when fixed via commit 714e155 and rerunning `gem install rspec`, worked fine.

The next step of installing the `galaaz` gem fails:

```
root@47c89260ca9a:/graalvm-demos/galaaz-ggplot# gem install galaaz
ERROR:  Error installing galaaz:
	invalid gem: package is corrupt, exception while verifying: invalid byte sequence in US-ASCII (ArgumentError) in /graalvm/languages/ruby/lib/gems/cache/galaaz-0.5.0.gem
```

Would need further investigation.

**Comment by eregon** [comment]
https://github.com/graalvm/graalvm-demos/commit/714e155c2fc6530646c1168aa36e50087786dafe is a huge hack, please do not do that.
Instead, run the post-install hook as documented and as shown in the post-install message:
https://github.com/oracle/truffleruby/blob/master/doc/user/installing-graalvm.md#installing-ruby-and-other-languages

**Comment by neomatrix369** [comment]
> [714e155](https://github.com/graalvm/graalvm-demos/commit/714e155c2fc6530646c1168aa36e50087786dafe) is a huge hack, please do not do that. Instead, run the post-install hook as documented and as shown in the post-install message: https://github.com/oracle/truffleruby/blob/master/doc/user/installing-graalvm.md#installing-ruby-and-other-languages

I totally agree, with it, I'm not a fan of it either, this one is a temporary way to move forward, till all the issues are resolved. I have run the `post-install-hook.sh` script following the docs, but it fails, I will follow your steps, and try again and report back.

**Comment by eregon** [comment]
Yes, this looks good.
AFAIK only `sudo apt-get install libssl-dev` is needed as mentioned on https://github.com/oracle/truffleruby/blob/master/doc/user/installing-libssl.md

> If these are correct, it would help to mention these dependencies on this page

They are already mentioned:
https://github.com/oracle/truffleruby/blob/master/doc/user/installing-graalvm.md#dependencies
But unfortunately that link is broken, I'll fix it. It should bring you to https://github.com/oracle/truffleruby/blob/master/README.md#dependencies

**Comment by eregon** [comment]
BTW `$GRAALVM_DIR/jre` means you're using Java 8, but that's already unsupported for the 21.3 release, so I would suggest to use 11 instead.

**Comment by neomatrix369** [comment]
> BTW `$GRAALVM_DIR/jre` means you're using Java 8, but that's already unsupported for the 21.3 release, so I would suggest to use 11 instead.
Yes the build I'm currently testing is Java 8 based, I will also run for Java 11. Maintaining Java 8 for demo apps that only run on Java 8 for now

**Comment by eregon** [comment]
> Did you rebuild the `polyglot` and `libpolyglot` images using `gu rebuild-images polyglot libpolyglot` (this is part of the post hook install step, see latter part of see https://github.com/oracle/truffleruby/blob/master/doc/user/installing-graalvm.md#dependencies) -- this takes a load of time on Linux (and inside the container, even with lots of RAM), at the moment it's failing to complete for me, I'll post the errors later on.

This is only necessary if you want to use polyglot/libpolyglot in `--native` mode.
Typically people use `--jvm --polyglot` as that removes the need to recompile any images.

**Comment by neomatrix369** [comment]
> 
> I found dependencies that I'm adding to the `Dockerfile` I will share separate once I have a successful build

I followed the steps mentioned in the docs kindly provided by you so far (above) and this is the outcome after running the post hook script:
```
root@f755aa023802:/graalvm-demos/galaaz-ggplot# gem install rspec
ERROR:  Loading command: install (RuntimeError)
	you may need to install the system OpenSSL library libssl - see https://github.com/oracle/truffleruby/blob/master/doc/user/installing-libssl.md (libssl.so.10: cannot open shared object file: No such file or directory)
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
```
I tried to look for the installed libraries and you can see the version numbering is slightly different, GraalVM is looking for `libssl.so.10` but the below are available instead:

```
root@f755aa023802:/graalvm-demos/galaaz-ggplot# find / -name *libssl.so*
/usr/lib/x86_64-linux-gnu/libssl.so.1.1
/usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
```
I must be missing a step I think.

**Comment by neomatrix369** [comment]
> Having libssl 10 installed is not great and should be avoided, so there is less risk to mix headers files and libs of different versions (but it should still work). Does the base image come with `libssl.so.1.0.2`? Which base image is it?

The base image is from the docker image `buildpack-deps:stretch-scm`, when updated with `apt-get` it brings down the versions of the libraries you see above.

**Comment by neomatrix369** [comment]
Both the gems (`rspec` and `galaaz`) install successfully after applying these changes: 2e1470e
f03fbea 0bcf891 5ac240e 8b7e9d5, in summary moving to `debian:buster` and installing the `locale` settings resolved the above reported issues.

But it still appears that if the underlying Linux distro is changed to another distro and the above steps may fail. Also setting `locale`, isn't a trivial step of setting `LANG="xxxx"` but adding the locale into the locale config and another step thereafter.

Also need a linux dependency `bzip2` in order for the `galaaz ...` command to progress, although now we have a Truffle/static lib related error when I run `galaaz master_list:scatter_plot`, see logs:

```
<---runs for 20 odd minutes, then the below error occurs -->

<--snipped-->
The downloaded source packages are in
	‘/tmp/Rtmpfj1YTD/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
unknown.r:1:in `library.dynam': libc++.so.1: cannot open shared object file: No such file or directory (com.oracle.truffle.nfi.backend.libffi.NFIUnsatisfiedLinkError) (RuntimeError)
Translated to internal error
	from unknown.r:1:in `loadNamespace'
<--snipped-->
```
Detailed logs, see [galaaz_master_list_demo_error.log](https://github.com/graalvm/graalvm-demos/files/7349978/galaaz_master_list_demo_error.log)

**Comment by eregon** [comment]
>  I suggest mentioning both these in the docs, otherwise it can be a struggle.

I updated https://github.com/oracle/truffleruby/blob/master/doc/user/utf8-locale.md recently, I think that should be clear.

Could you open a separate issue for what you get now?
Also that looks like an issue from R, not Ruby.

**Comment by neomatrix369** [comment]
> To fix this error:
> 
> ```
> unknown.r:1:in `library.dynam': libc++.so.1: cannot open shared object file: No such file or directory (com.oracle.truffle.nfi.backend.libffi.NFIUnsatisfiedLinkError) (RuntimeError)
> ```
> 
> you will need to install the `libc++-dev` package on the system.

Thanks @steve-s, I'm rebuilding and testing it now
