### ISSUE TITLE
spring-r: issue with building and running demo

### ISSUE THREAD

**Issue by neomatrix369** [graalvm/graalvm-demos#96]
On the back of the PR #93, building and running the `spring-r` demo gives issues, the steps in the README were followed, see https://github.com/graalvm/graalvm-demos/tree/master/spring-r#preparation.

On running `mvn spring-boot:run -Dgraalvm.version=21.2.0`, we encounter the below error message:

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'springRApplication': Unsatisfied dependency expressed through field 'plotFunction'; 
nested exception is org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'getPlotFunction' defined in org.graalvm.demos.springr.SpringRApplication:
Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: 
Failed to instantiate [java.util.function.Function]: Circular reference involving containing bean 'springRApplication' 
- consider declaring the factory method as static for independence from its containing instance. 
Factory method 'getPlotFunction' threw exception; nested exception is org.graalvm.polyglot.Polyglot
...
<---snipped, saved into log file-->
```

Will need to be checked separately, see [logs](https://github.com/graalvm/graalvm-demos/files/7325405/spring-r-demo.log)

**Comment by olyagpl** [comment]
@neomatrix369, I've tested this demo with GraalVM EE 21.2.0.1 Java 11, and it ran flawlessly this time:
![Screenshot 2021-10-12 at 23 12 20](https://user-images.githubusercontent.com/31922163/137023857-0a97c2a3-3368-4e0a-be32-df001235663f.png)
